apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-common
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: default
  source:
    path: components/vault-common/base
    repoURL: https://github.com/IBM-Security/verify-gitops-demo
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# Made with Bob