apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: ivia-secrets
  namespace: ibm-verify
spec:
  type: kv-v2
  mount: ibm-verify
  path: ivia-secrets
  destination:
    name: ivia-secrets
    create: true
  refreshAfter: 30s
  vaultAuthRef: ibm-verify-auth

# Made with Bob
